### ISSUE TITLE
Viewport focus annotation erratic behaviour

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/iiif-manifest-editor-components#14]
The way this works is really inconsistent.

After adding one, id expect it to be visible.

Often I cannot resize the square.

Toggling visibility is really hard.

Sometimes the added area is huge and uncontrollable, sometimes tiny.

Not clear if it works in preview

**Comment by adam-digirati** [comment]
Please try it with clear cache, and if you could clear all the app storage on the inspector's Application tab. 

<img width="1224" alt="Screenshot 2019-03-27 at 16 14 11" src="https://user-images.githubusercontent.com/33420570/55093031-8a36fd00-50ab-11e9-94bc-2fbeb02a5415.png">
