### ISSUE TITLE
HTML annotations text not rendering fully in annotated zoom

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/iiif-manifest-editor-components#16]

**Comment by adam-digirati** [comment]
You may need to scroll? I don't know. 

<img width="1896" alt="Screenshot 2019-03-27 at 16 26 48" src="https://user-images.githubusercontent.com/33420570/55093950-4cd36f00-50ad-11e9-9423-dd1f215feee0.png">
<img width="1242" alt="Screenshot 2019-03-27 at 16 27 03" src="https://user-images.githubusercontent.com/33420570/55093962-5361e680-50ad-11e9-92d7-f31dc6f0de39.png">

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/33420570/55094303-134f3380-50ae-11e9-9497-9d0e679ef7c3.gif)

**Comment by villedigirati** [comment]
Things like using B style don't persist.

There's also a weird issue im getting with the annotations becoming the same (see backlog)

**Comment by adam-digirati** [comment]
B style is artificially suppressed on the demo page, I assume v&a will enable it later, but at the moment we are requesting the stylesheet from vam site for the preview. So it is not an issue of the manifest editor.

For the other second line you opened another ticket, so i'm closing this one.
