### ISSUE TITLE
Annotated zoom - adding multiple text annotations does not work after previewing - the content is same for each text annotation

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/iiif-manifest-editor-components#23]

**Comment by villedigirati** [comment]
Not sure if its to do with using the html option (it was fine for awhile, but when I added html content, previewed, came back, all the content had become the same again in both of my annotations

**Comment by adam-digirati** [comment]
good catch, there was an issue with way the data has been updated, and the object reference on annotation bodies swapped back if the annotation has been edited. Fixed

**Comment by villedigirati** [comment]
I cleared cache etc but still getting issue...

**Comment by adam-digirati** [comment]
I have insufficient information to I can't reproduce the same issue you have then.
